version: "3.8"
services:
  api:
    build: ./api
    container_name: dockerbasic_api_c
    ports:
      - "4000:4000"
    volumes:
      - ./api:/api
      - /api/node_modules

  app:
    build: ./app
    container_name: dockerbasic_app_react_c
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
